import type { ArchetypeDef, ArchetypeId } from './types';

/**
 * Original enemy archetypes. Each one exists to force a different mechanical
 * habit, and difficulty scales their *behaviour* (reaction, prediction, aim
 * error, spacing, aggression) rather than their health bar.
 */
export const ARCHETYPES: Record<ArchetypeId, ArchetypeDef> = {
  ranger: {
    id: 'ranger',
    name: 'RANGER',
    blurb: 'Disciplined ranged trader. Holds the edge of its range and punishes standing still.',
    teaches: 'Spacing and attack-move discipline',
    color: '#5ce1a8',
    baseHp: 560,
    radius: 30,
    moveSpeed: 335,
    attack: { attackSpeed: 0.72, windupRatio: 0.26, backswingRatio: 0.34, range: 520, damage: 42, projectileSpeed: 1450 },
    preferredRange: 470,
    aggression: 0.42,
    abilityCd: 6.5,
  },
  diver: {
    id: 'diver',
    name: 'DIVER',
    blurb: 'Closes distance in a straight line and commits. Rewards clean kiting angles.',
    teaches: 'Kiting under pressure',
    color: '#ff7a5c',
    baseHp: 660,
    radius: 34,
    moveSpeed: 372,
    attack: { attackSpeed: 0.85, windupRatio: 0.22, backswingRatio: 0.3, range: 155, damage: 46, projectileSpeed: 0 },
    preferredRange: 110,
    aggression: 0.95,
    abilityCd: 7.5,
  },
  artillery: {
    id: 'artillery',
    name: 'ARTILLERY',
    blurb: 'Sits far back and drops telegraphed zones. Never lets you stand still.',
    teaches: 'Reading telegraphs while doing something else',
    color: '#c48bff',
    baseHp: 430,
    radius: 29,
    moveSpeed: 300,
    attack: { attackSpeed: 0.5, windupRatio: 0.34, backswingRatio: 0.34, range: 880, damage: 38, projectileSpeed: 900 },
    preferredRange: 790,
    aggression: 0.18,
    abilityCd: 5.0,
  },
  controller: {
    id: 'controller',
    name: 'CONTROLLER',
    blurb: 'Throws roots and slow fields. Getting clipped turns a good run into a bad one.',
    teaches: 'Skillshot dodging and repositioning',
    color: '#58c6ff',
    baseHp: 500,
    radius: 31,
    moveSpeed: 322,
    attack: { attackSpeed: 0.6, windupRatio: 0.3, backswingRatio: 0.32, range: 600, damage: 34, projectileSpeed: 1250 },
    preferredRange: 555,
    aggression: 0.36,
    abilityCd: 5.5,
  },
  duelist: {
    id: 'duelist',
    name: 'DUELIST',
    blurb: 'Fast, twitchy, dashes in and out. Punishes sloppy target switching.',
    teaches: 'Target switching and reaction speed',
    color: '#ffd166',
    baseHp: 590,
    radius: 31,
    moveSpeed: 358,
    attack: { attackSpeed: 1.05, windupRatio: 0.2, backswingRatio: 0.28, range: 180, damage: 30, projectileSpeed: 0 },
    preferredRange: 150,
    aggression: 0.82,
    abilityCd: 4.5,
  },
  juggernaut: {
    id: 'juggernaut',
    name: 'JUGGERNAUT',
    blurb: 'Slow, heavy, inevitable. Slams the ground and takes space away from you.',
    teaches: 'Space management and patience',
    color: '#ff5f8f',
    baseHp: 1060,
    radius: 41,
    moveSpeed: 318,
    attack: { attackSpeed: 0.62, windupRatio: 0.3, backswingRatio: 0.34, range: 170, damage: 62, projectileSpeed: 0 },
    preferredRange: 125,
    aggression: 0.88,
    abilityCd: 6.0,
  },
};

export const ARCHETYPE_LIST = Object.values(ARCHETYPES);
