import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PATCH_NOTES, TAG_LABEL, VERSION, type PatchTag } from '../src/patchnotes/notes';

/**
 * Renders CHANGELOG.md from the same list the client reads.
 *
 * Two hand-maintained copies of a release history diverge within one release;
 * one source and a renderer cannot. Run `npm run changelog` after editing
 * `src/patchnotes/notes.ts`, and commit both.
 */

const TAG_ORDER: PatchTag[] = ['added', 'changed', 'fixed'];

const lines: string[] = [
  '# Changelog',
  '',
  '<!-- Generated by `npm run changelog` from src/patchnotes/notes.ts. Do not edit by hand. -->',
  '',
  'Every release, newest first — what was added, what changed under you, and what was',
  'broken and is not any more. The same list is readable in the client under the version',
  'chip in the top bar.',
  '',
  `Currently shipping **v${VERSION}**.`,
  '',
  'Versions before 1.2.0 are assigned retroactively from the commit history: the project',
  'shipped continuously before it started numbering itself.',
  '',
];

for (const entry of PATCH_NOTES) {
  lines.push(`## v${entry.version} — ${entry.name}`, '', `*${entry.date}*`, '', entry.headline, '');
  for (const tag of TAG_ORDER) {
    const section = entry.sections.find((s) => s.tag === tag);
    if (!section || section.items.length === 0) continue;
    lines.push(`### ${TAG_LABEL[tag]}`, '');
    for (const item of section.items) lines.push(`- ${item}`);
    lines.push('');
  }
}

// Relative to the package root, not to the bundle — esbuild puts the bundle
// under node_modules/.cache, and `import.meta.url` would follow it there.
writeFileSync(resolve(process.cwd(), 'CHANGELOG.md'), lines.join('\n'));
console.log(`CHANGELOG.md written — ${PATCH_NOTES.length} releases, current v${VERSION}`);
